### ISSUE TITLE
Info on the samples

### ISSUE THREAD

**Issue by FalconBry** [mikeoliphant/DryGuitarSamples#1]
Hello,
Thank you for the providing the guitar samples.
I have a few questions;
1. Could you tell me the exact signal chain you used to record the samples?
2. Do you still have the original recordings in 24\32 bit float format or at least higher then 16-bit wav?
3. What guitar, pickups did you use? (sounds like humbuckers)

(p.s. I came here via the DKBuilder discussion)

**Comment by mikeoliphant** [comment]
Hmm - I'm trying to remember. I'm pretty sure that I used a Boss GT-1 (with no effects on) as an audio interface and the guitar was an Epiphone Les Paul (so yes, humbuckers).

Sorry, I don't have the files at a higher bit depth.
